url: https://www.aos-usa.com
baseurl: /home

# Site settings
title: AOS Technology
email: info@aos-usa.com
description: Cloud Consultant | Security and Compliance Assessments | Business Continuity and Disaster Recovery Plans | M365 Migrations | Azure | VMware | Nutanix


# Team names, titles and social links
people:
- name: Sherif Alghali
  pic: 1
  position: Principal Consultant
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/salghali/

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: 
  - title: facebook
    url:
  - title: linkedin
    url: https://www.linkedin.com/company/aos-technology
  - title: github
    url:

# Postal address (add as many lines as necessary)
address:
  - line: 2401 Fountain View Dr.
  - line: Suite 312
  - line: Houston, TX 77057

# Build settings
markdown: kramdown
permalink: pretty